[package]
name = "testcrate"
version = "0.2.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]
license = "MIT"
repository = "https://github.com/mersinvald/singleton-rs"

[dependencies]
singletonum = { path = "../singletonum" }
